name: Solipsism Studio
description: Solispsim Studio is a home studio offering mixing services for all types of metal and rock
permalink: pretty

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - todo
  - css/_main.css
  - package.json
